routes/admin.php
<?php

use App\Helpers\Helper;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\Dashboard;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::Group(
    [
        'prefix' => Helper::option('admin_path', 'admin'),
        'middleware' => Helper::option('verify_email') === '1' ? ['verified', 'auth'] : ['auth']
    ],
    function () {
        Route::get('/', [Dashboard::class, 'index'])->name('AppDashboard');
        Route::resource('roles', RoleController::class);
        Route::resource('users', UserController::class);
        Route::get('users/deactivate/{user}', [UserController::class, 'deactivate'])->name('users.deactivate');
        Route::get('users/activate/{user}', [UserController::class, 'activate'])->name('users.activate');
        Route::get('users/role_changed/{role}', [UserController::class, 'role_changed'])->name('users.role_changed');
        Route::get('settings', [SettingController::class, 'index'])->name('settings.index');
        Route::post('settings/general', [SettingController::class, 'general'])->name('settings.general');
        Route::get('settings/email', [SettingController::class, 'email'])->name('settings.email.get');
        Route::post('settings/email', [SettingController::class, 'email'])->name('settings.email');
        Route::get('settings/authentication', [SettingController::class, 'authentication'])->name('settings.authentication.get');
        Route::post('settings/authentication', [SettingController::class, 'authentication'])->name('settings.authentication');
        Route::get('settings/localization', [SettingController::class, 'localization'])->name('settings.localization.get');
        Route::post('settings/localization', [SettingController::class, 'localization'])->name('settings.localization');
        Route::get('settings/menage-site', [SettingController::class, 'managesite'])->name('settings.menagesite.get');
        Route::post('settings/menage-site', [SettingController::class, 'managesite'])->name('settings.managesite');
        Route::get('profile', [UserController::class, 'profile'])->name('profile');
        Route::post('profile', [UserController::class, 'update_profile'])->name('update_profile');

    }
);

routes/user.php
<?php

use App\Helpers\Helper;
use Illuminate\Support\Facades\Route;

Route::Group(
    [
        'prefix' => Helper::option('user_path', 'user'),
        'middleware' => Helper::option('verify_email') === '1' ? ['verified', 'auth'] : ['auth']
    ],
    function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('UserDashboard');
    }
);

routes/web.php
<?php

use App\Helpers\Helper;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return redirect()->route('AppDashboard');
})->name('home');


require __DIR__ . '/auth.php';
require __DIR__ . '/admin.php';
require __DIR__ . '/user.php';

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    use HasFactory,Blameable,SoftDeletes;

    protected $fillable = [
        'name', 'access'
    ];

    public function user()
    {
        return $this->hasMany('App\Models\User', 'role');
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Helper;
use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Helper::authorize('accessView','roles');
        $data['title']=__('admin.roles');
        $data['roles'] = Role::all();
        return view('admin.roles.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Helper::authorize('create', 'roles');
        $data['title'] = __('admin.new', ['name' => __('admin.roles')]);
        return view('admin.roles.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Helper::authorize('create', 'roles');
        $request->validate([
            'role_name' => ['required', 'max:255', 'unique:roles,name'],
        ]);
        $permiss = NULL;
        if ($request->permissions) {
            $permiss = serialize($request->permissions);
        }
        Role::create([
            'name' => $request->role_name,
            'access' => $permiss,
        ]);
        Helper::alert(__('alert.addDone'));
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Helper::authorize('update', 'roles');
        $roles = Role::find($id);
        if (!$roles || $id == '1') {
            Helper::alert(__('alert.not_found'), 'danger');
            return redirect()->route('roles.index');
        }
        $data['role'] = $roles;
        $data['title'] = __('admin.update') . ' ' . __('admin.roles') . ' : ' . $roles->name;
        return view('admin.roles.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        Helper::authorize('update', 'roles');
        $roles = Role::find($id);
        if (!$roles || $id == '1') {
            Helper::alert(__('alert.not_found'), 'danger');
            return redirect()->route('roles.index');
        }
        $request->validate([
            'role_name' => ['required', 'max:255', Rule::unique('roles', 'name')->ignore($roles->id, 'id')],
        ]);
        $roles->name = $request->role_name;
        $permiss = NULL;
        if ($request->permissions) {
            $permiss = serialize($request->permissions);
        }
        $roles->access = $permiss;
        $roles->save();

        if ($request->update_user_permissions == '1') {
            $roles = Role::find($id);
            $permissions = new UserController;
            $listUser = $roles->user()->get();
            foreach ($listUser as $user) {
                $permissions->update_permissions($request->permissions, $user->id);
            }
        }
        Helper::alert(__('alert.saveDone'));
        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Helper::authorize('delete', 'roles');
        $roles = Role::find($id);
        if (!$roles || $id == '1') {
            Helper::alert(__('admin.not_found'), 'danger');
            return redirect()->route('roles.index');
        }
        if ($roles->user()->count() > 0) {
            Helper::alert(__('admin.role_is_used',['number' => $roles->user()->count()]),'danger');
            return redirect()->route('roles.index');
        }
        Role::destroy($id);
        Helper::alert(__('alert.deleteDone'));
        return redirect()->route('roles.index');
    }
}

resources/views/admin/roles/form.blade.php
@php
    $page_title=$title ?? '';
@endphp
@extends('admin.layout.app')
@section('title', $page_title)

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('roles.index') }}"> {{__('admin.roles') }}</a></li>
<li class="breadcrumb-item active">{{$page_title}}</li>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card mb-3">
            <form action="{{ isset($role) ? route('roles.update',['role'=>$role->id]) : route('roles.store') }}" enctype="multipart/form-data" method="POST">
                <div class="card-body">
                    @if (isset($role))
                        @method('PATCH')
                    @endif
                    @csrf
                    {!!Helpers::displayAlert()!!}
                    <div class="row">
                        <div class="form-group col-md-9 col-sm-12">
                            @if (isset($role) && $role->user()->count()>0)
                            <div class="alert alert-info dark mb-3">
                                <div class="col-form-label">{{ __('alert.change_role_permission_warning') }}</div>
                                <div class="form-group m-checkbox-inline mb-0 custom-radio-ml">
                                    <div class="checkbox checkbox-info">
                                        <input id="update_user_permissions" type="checkbox" name="update_user_permissions" value="1" data-original-title="" title="">
                                        <label class="mb-0" for="update_user_permissions"><b>{{ __('admin.role_update_user_permissions') }}</b></label>
                                    </div>
                                </div>
                            </div>
                            @endif
                            <div class="form-group mb-3">
                                <input class="form-control @error('role_name') is-invalid @enderror" type="text" id="role_name" value="{{ isset($role) ? $role->name : old('role_name') }}" name="role_name" required="" placeholder="{{ __('admin.role_name') }}">
                                @error('role_name')
                                    <div class="invalid-feedback" >
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @enderror
                            </div>
                            @php
                                $permissionsData['role']=isset($role) ? $role : null;
                            @endphp
                            @include('admin.users.permissions',$permissionsData)
                            <div class="form-footer text-right">
                                <button class="btn btn-primary px-4 shadow-none">{{ __('admin.save') }}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- end row -->
@endsection

resources/views/admin/roles/index.blade.php
@php
    $page_title=$title ?? '';
@endphp
@extends('admin.layout.app')
@section('title',  $page_title)

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('AppDashboard') }}"> {{__('admin.dashboard') }}</a></li>
<li class="breadcrumb-item active">{{$page_title}}</li>
@endsection

@section('style')
<link rel="stylesheet" type="text/css" href="{{asset('admin-style/plugins/datatables/datatables.min.css')}}" />
<link rel="stylesheet" type="text/css" href="{{asset('admin-style/plugins/sweet-alert/sweetalert2.css')}}">
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card mb-3">
            <div class="card-header">
                <span class="pull-left">
                    @can('create','roles')
                    <a href="{{ route('roles.create') }}" class="shadow-none btn btn-primary btn-sm text-white px-3" ><i class="fas fa-user-check" aria-hidden="true"></i> {{ __('admin.new',['name'=>__('admin.roles')]) }}</a>
                    @endcan
                </span>
            </div>
            <div class="card-body">
                 {!!Helpers::displayAlert()!!}
                 <div class="table-responsive mb-3">
                     <table class="table table-hover display table-loading" id="data-table">
                        <thead class="display-none">
                            <tr>
                                <th scope="col" style="width:5%">#</th>
                                <th scope="col">{{ __('admin.roles') }}</th>
                                <th scope="col">{{ __('admin.users') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $no=1;
                            @endphp
                            @foreach ($roles as $role)
                            @php
                                $row_action=[];
                            @endphp
                            @can('update','roles')
                            @php
                            $row_action[] = [
                                'title' => __('admin.edit'),
                                'class' => 'text-primary',
                                'link'  => route('roles.edit',['role'=>$role->id]),
                            ];
                            @endphp
                            @endcan
                            @if ($role->user()->count()<1)
                                @can('delete','roles')
                                @php
                                    $row_action[] = [
                                        'title' => __('admin.delete'),
                                        'class' => 'text-danger',
                                        'link'  => route('roles.destroy',['role'=>$role->id]),
                                        'onclick'=>"deleteData(".$role->id.")"
                                    ];
                                @endphp
                                @endcan
                            @endif
                            <tr>
                                <td><b>{{ $no++ }}</b></td>
                                <td scope="row">
                                    <b>{{ $role->name }}</b>
                                    @if ($role->id !='1')
                                        @include('admin.layout.action',['link'=>$row_action])
                                        <form name="formDelete{{ $role->id }}" id="formDelete{{ $role->id }}" action="{{ route('roles.destroy',['role'=>$role->id]) }}" method="POST">
                                            @method("DELETE")
                                            @csrf
                                        </form>
                                    @endif
                                </td>
                                <td>{{ number_format($role->user()->count()) }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                     </table>
                 </div>
            </div>
        </div>
    </div>
</div>
{{-- @include('admin.layout.filemanager') --}}
<!-- end row -->
@endsection

@section('script')
<script src="{{asset('admin-style/plugins/datatables/datatables.min.js')}}"></script>
<script src="{{asset('admin-style/plugins/sweet-alert/sweetalert.min.js')}}"></script>
<script>
     $(document).ready(function() {
        $('#data-table').DataTable();
    });
    function deleteData(dat){
        swal({
            title: '{{ __("admin.confirm")}}',
            icon: 'warning',
            buttons: {
                cancel: {
                    text: "{{ __('admin.no')}}",
                    value: null,
                    visible: true,
                    className: "btn btn-danger",
                    closeModal: true,
                },
                confirm: {
                    text: "{{ __('admin.yes')}}",
                    value: true,
                    visible: true,
                    className: "btn btn-primary",
                    closeModal: false
                }
            },
            closeOnEsc: false,
            closeOnClickOutside: false,
        }).then((value) => {
            if (value === true) {
                document.getElementById("formDelete"+dat).submit();
            }
        }).catch(err => {
            if (err) {
                swal("Oops!", " {{ __('admin.error_message') }}", "error");
            } else {
                swal.stopLoading();
                swal.close();
            }
        });
    }
</script>
@endsection