routes/admin.php
<?php

use App\Helpers\Helper;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\Dashboard;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::Group(
    [
        'prefix' => Helper::option('admin_path', 'admin'),
        'middleware' => Helper::option('verify_email') === '1' ? ['verified', 'auth'] : ['auth']
    ],
    function () {
        Route::get('/', [Dashboard::class, 'index'])->name('AppDashboard');
        Route::resource('roles', RoleController::class);
        Route::resource('users', UserController::class);
        Route::get('users/deactivate/{user}', [UserController::class, 'deactivate'])->name('users.deactivate');
        Route::get('users/activate/{user}', [UserController::class, 'activate'])->name('users.activate');
        Route::get('users/role_changed/{role}', [UserController::class, 'role_changed'])->name('users.role_changed');
        Route::get('settings', [SettingController::class, 'index'])->name('settings.index');
        Route::post('settings/general', [SettingController::class, 'general'])->name('settings.general');
        Route::get('settings/email', [SettingController::class, 'email'])->name('settings.email.get');
        Route::post('settings/email', [SettingController::class, 'email'])->name('settings.email');
        Route::get('settings/authentication', [SettingController::class, 'authentication'])->name('settings.authentication.get');
        Route::post('settings/authentication', [SettingController::class, 'authentication'])->name('settings.authentication');
        Route::get('settings/localization', [SettingController::class, 'localization'])->name('settings.localization.get');
        Route::post('settings/localization', [SettingController::class, 'localization'])->name('settings.localization');
        Route::get('settings/menage-site', [SettingController::class, 'managesite'])->name('settings.menagesite.get');
        Route::post('settings/menage-site', [SettingController::class, 'managesite'])->name('settings.managesite');
        Route::get('profile', [UserController::class, 'profile'])->name('profile');
        Route::post('profile', [UserController::class, 'update_profile'])->name('update_profile');

    }
);

routes/user.php
<?php

use App\Helpers\Helper;
use Illuminate\Support\Facades\Route;

Route::Group(
    [
        'prefix' => Helper::option('user_path', 'user'),
        'middleware' => Helper::option('verify_email') === '1' ? ['verified', 'auth'] : ['auth']
    ],
    function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('UserDashboard');
    }
);

routes/web.php
<?php

use App\Helpers\Helper;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return redirect()->route('AppDashboard');
})->name('home');


require __DIR__ . '/auth.php';
require __DIR__ . '/admin.php';
require __DIR__ . '/user.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable,SoftDeletes;
    use Blameable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'status',
        'role',
        'address',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles($col = 'name')
    {
        $roles = $this->belongsTo('App\Models\Role', 'role');
        return $roles->first()->$col;
    }

    public function permissions()
    {
        return $this->hasMany('App\Models\Permission', 'user_id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Helper;
use App\Http\Controllers\Controller;
use App\Models\Permission;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    protected function validator(array $data, $id = NULL)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'phone' => ['min:6'],
            'email' => ['required', 'string', 'email', 'max:255', $id ? Rule::unique('users')->ignore($id, 'id') : 'unique:users'],
            'password' => $id ? [] : ['required', 'string', 'min:5'],
        ]);
    }

    public function profile(){
        $data['title'] = __('lang.profile');
        return view('admin.users.profile', $data);
    }

    public function update_profile(Request $request){
        $user = User::find(Auth::user()->id);
        if (empty($user)) {
            return redirect()->route('AppDashboard');
        }
        $request->validate([
            'name' => ['required', 'max:255'],
            'phone' => ['min:6'],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($user->id, 'id')],
        ]);
        if (!empty($request->password)) {
            $request->validate([
                'password' => ['required', 'min:5'],
            ]);
            $user->password = Hash::make($request->password);
        }
        $user->name = $request->name;
        $user->phone = $request->phone;
        $user->email = $request->email;
        $user->save();
        Helper::alert(__('alert.saveDone'));
        return redirect()->route('profile');
    }

    public function update_permissions($permissions = [], $id = NULL)
    {
        Permission::where('user_id', $id)->delete();
        if (is_array($permissions)) {
            foreach ($permissions as $key => $value) {
                foreach ($value as $item) {
                    Permission::create([
                        'user_id' => $id,
                        'module' => $key,
                        'access' => $item,
                    ]);
                }
            }
        }
        return true;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        Helper::authorize('delete', 'users');
        if ($request->ajax()) {
            $query=User::query();
            return DataTables::of($query)
                ->addColumn('displayName',function($rows){
                $row_action = [];
                $formDelete='';
                if (Auth::user()->can('update', 'users') && $rows->id != 1) {
                    $row_action[] = [
                        'title' => __('admin.edit'),
                        'class' => 'text-info',
                        'link' => route('users.edit', ['user' => $rows->id]),
                    ];
                }
                if (Auth::user()->can('update', 'users') && $rows->id != 1) {
                    if ($rows->status == '1') {
                        $row_action[] = [
                            'title' => __('admin.deactivate'),
                            'class' => 'text-danger',
                            'link'  => route('users.deactivate', ['user' => $rows->id]),
                        ];
                    } elseif ($rows->status == '0') {
                        $row_action[] = [
                            'title' => __('admin.activate'),
                            'class' => 'text-success',
                            'link'  => route('users.activate', ['user' => $rows->id]),
                        ];
                    }
                }
                if (Auth::user()->can('delete', 'users') && $rows->id != 1) {

                    $row_action[] = [
                        'title' => __('admin.delete'),
                        'class' => 'text-danger',
                        'link'  => route('users.destroy', ['user' => $rows->id]),
                        'onclick' => "deleteData(" . $rows->id . ")"
                    ];
                    $formDelete = "<form name='formDelete" . $rows->id . "' id='formDelete" . $rows->id . "' action='" . route('users.destroy', ['user' => $rows->id]) . "' method='POST'>";
                    $formDelete .= method_field('delete');
                    $formDelete .= csrf_field();
                    $formDelete .= "</form>";
                }
                return "<b>" . ucwords($rows->name) . "</b>".Helper::action_links($row_action) . $formDelete;
                })
                ->editColumn('role', function ($rows) {
                    return $rows->roles();
                })
                ->editColumn('status', function ($rows) {
                    if ($rows->status == '1') {
                        $status_user = "<label class='badge badge-success'>" . __('active') . "</label>";
                    } elseif ($rows->status == '0') {
                        $status_user = "<label class='badge badge-danger'>" . __('inactive') . "</label>";
                    }
                    return $status_user;
                })
            ->rawColumns(['displayName', 'roles', 'status'])
            ->make();
        }
        $data['title'] = __('admin.users');
        return view('admin.users.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Helper::authorize('create', 'users');
        $data['title']=__('admin.new',['Name'=>__('admin.users')]);
        $data['roles'] = Role::all();
        return view('admin.users.form',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Helper::authorize('create', 'users');
        $this->validator($request->all())->validate();
        $create = User::factory()->createQuietly([
            'name' => $request['name'],
            'phone' => $request['phone'],
            'email' => $request['email'],
            'email_verified_at' => now(),
            'status' => '1',
            'role' => $request['role'],
            'created_by' => Auth::user()->id,
            'updated_by' => Auth::user()->id,
            'password' => Hash::make($request['password']),
        ]);
        $this->update_permissions($request->permissions, $create->id);
        Helper::alert(__('alert.addDone'));
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Helper::authorize('update', 'users');
        $users = User::find($id);
        if (!$users || $id == '1') {
            Helper::alert(__('admin.not_found'), 'danger');
            return redirect()->route('users.index');
        }
        $data['user'] = $users;
        $data['title'] = __('admin.update') . ' ' . __('admin.users') . ' : ' . $users->name;
        $data['roles'] = Role::all();
        return view('admin.users.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Helper::authorize('update', 'users');
        $users = User::find($id);
        if (!$users || $id == '1') {
            Helper::alert(__('admin.not_found'), 'danger');
            return redirect()->route('users.index');
        }
        $this->validator($request->all(), $id)->validate();
        $users->name = $request->name;
        $users->phone = $request->phone;
        $users->email = $request->email;
        $users->role = $request->role;
        if (!empty($request->password)) {
            $users->password = Hash::make($request->password);
        }
        $users->save();
        $this->update_permissions($request->permissions, $id);
        Helper::alert(__('alert.saveDone'));
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Helper::authorize('delete', 'users');
        $users = User::find($id);
        if (!$users || $users == '1') {
            Helper::alert(__('admin.not_found'), 'danger');
            return redirect()->route('users.index');
        }
        Permission::where('user_id', $id)->delete();
        User::destroy($id);
        Helper::alert(__('alert.deleteDone'));
        return redirect()->route('users.index');
    }

    public function deactivate($id = NULL, Request $request)
    {
        Helper::authorize('update', 'users');
        $user = User::find($id);
        if (empty($user)) {
            Helper::alert(__('admin.not_found'), 'danger');
            return redirect()->route('users.index');
        }

        $user->status = '0';
        $user->save();
        Helper::alert(__('alert.saveDone'));
        return redirect()->route('users.index');
    }
    public function activate($id = NULL, Request $request)
    {
        Helper::authorize('update', 'users');
        $user = User::find($id);
        if (empty($user)) {

resources/views/admin/users/form.blade.php
@php
    $page_title=$title ?? '';
@endphp
@extends('admin.layout.app')
@section('title', $page_title)

@section('style')
<link href="{{asset('admin/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('users.index') }}"> {{__('admin.users') }}</a></li>
<li class="breadcrumb-item active">{{$page_title}}</li>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card mb-3">
            <form action="{{ isset($user) ? route('users.update',['user'=>$user->id]) : route('users.store') }}" enctype="multipart/form-data" method="POST">
                <div class="card-body">
                    @if (isset($user))
                        @method('PATCH')
                    @endif
                    @csrf
                    {!!Helpers::displayAlert()!!}
                    <div class="row">
                        <div class="form-group col-md-5 col-sm-12">
                            <div class="form-group mb-3">
                                <input class="form-control shadow-none @error('name') is-invalid @enderror" type="text" id="name" value="{{ old('name') ?? (isset($user) ? $user->name:'')  }}" name="name" required="" placeholder="{{ __('admin.name') }}" autocomplete="off">
                                @error('name')
                                    <div class="invalid-feedback" >
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <input class="form-control shadow-none @error('phone') is-invalid @enderror" type="text" id="phone" value="{{ old('phone') ?? (isset($user) ? $user->phone:'') }}" name="phone" placeholder="{{ __('admin.phone') }}" autocomplete="off">
                                @error('phone')
                                    <div class="invalid-feedback" >
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <input class="form-control shadow-none @error('email') is-invalid @enderror" type="email" id="email" value="{{ old('email') ?? (isset($user) ? $user->email:'') }}" name="email" required="" placeholder="{{ __('E-Mail Address') }}" autocomplete="off">
                                @error('email')
                                    <div class="invalid-feedback" >
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <input class="form-control shadow-none @error('password') is-invalid @enderror" type="password" id="password" value="" name="password" {{ isset($user) ? '': 'required' }} placeholder="{{ __('Password') }}">
                                @if (isset($user))
                                <small id="passwordHelp" class="form-text text-muted">({{ trans('admin.leave_empty_not_to_change') }})</small>
                                @endif
                                @error('password')
                                    <div class="invalid-feedback" >
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <select class="w-100 form-control shadow-none select2 @error('role') is-invalid @enderror" id="role" name="role" required="">
                                    <option value="" disabled selected>{{ __('admin.select',['name' => __('admin.roles')]) }}</option>
                                    @foreach ($roles as $item)
                                    <option value="{{ $item->id }}" {{ isset($user) && $user->role==$item->id ? "selected" : '' }}>{{ ucwords($item->name) }}</option>
                                    @endforeach
                                </select>
                                @error('role')
                                    <div class="invalid-feedback" >
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @enderror
                            </div>
                            <div class="form-footer text-right">
                                <button class="btn btn-primary px-4 shadow-none">{{ __('admin.save') }}</button>
                            </div>
                        </div>
                        <div class="form-group col-md-7 col-sm-12 border-left">
                            @php
                                $permissionsData['user']=isset($user) ? $user : null;
                            @endphp
                            @include('admin.users.permissions',$permissionsData)
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- end row -->
@endsection

@section('script')
<script src="{{asset('admin/plugins/select2/js/select2.min.js')}}"></script>
<script>
    $(document).ready(function () {
        $('.select2').select2();
    });
    $(function() {
        $('select[name="role"]').on('change', function() {
            var roleid = $(this).val();
            var url = '<?php echo route("users.role_changed",["role"=>":id"]) ;?>';
            url = url.replace(':id', roleid);
            if (roleid == '' || roleid == '1') {
                $('.roles').find('input').prop('disabled', true).prop('checked', false);
            } else {
                $('.roles').find('input').prop('disabled', false).prop('checked', false);
            }

            change_roles_permissions(url, roleid, true);
        });
    })
</script>
@endsection

resources/views/admin/users/index.blade.php
@php
    $page_title=$title ?? '';
@endphp
@extends('admin.layout.app')
@section('title', $page_title)

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('AppDashboard') }}"> {{__('admin.dashboard') }}</a></li>
<li class="breadcrumb-item active">{{$page_title}}</li>
@endsection

@section('style')
<link rel="stylesheet" type="text/css" href="{{asset('admin-style/plugins/datatables/datatables.min.css')}}" />
<link rel="stylesheet" type="text/css" href="{{asset('admin-style/plugins/sweet-alert/sweetalert2.css')}}">
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card mb-3">
            <div class="card-header">
                <span class="pull-left">
                    @can('create','users')
                    <a href="{{ route('users.create') }}" class="shadow-none btn btn-primary btn-sm text-white px-3" ><i class="fas fa-user-plus" aria-hidden="true"></i> {{ __('admin.new',['name'=>__('admin.users')]) }}</a>
                    @endcan
                </span>
            </div>
            <div class="card-body">
                 {!!Helpers::displayAlert()!!}
                 <div class="table-responsive mb-3">
                    <table class="table table-hover display table-loading" id="data-table">
                        <thead class="display-none">
                            <tr>
                                <th scope="col" style="width:5%">#</th>
                                <th scope="col">{{ __('admin.name') }}</th>
                                <th scope="col">{{ __('E-mail Address') }}</th>
                                <th scope="col">{{ __('admin.roles') }}</th>
                                <th scope="col">{{ __('admin.status') }}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
@endsection
@section('script')
<script src="{{asset('admin-style/plugins/datatables/datatables.min.js')}}"></script>
<script src="{{asset('admin-style/plugins/sweet-alert/sweetalert.min.js')}}"></script>
<script>
    var datatable=$("#data-table").DataTable({
        autoWidth: false,
        processing:true,
        serverside:true,
        ordering:true,
        ajax:{
            url:'{!! url()->current() !!}'
        },
        columns:[
            {data:'id',name:'id',width:'6%'},
            {data:'displayName',name:'displayName'},
            {data:'email',name:'email',width:'35%'},
            {data:'role',name:'role',width:'15%'},
            {data:'status',name:'status',width:'10%'},
        ],

    })
</script>
<script>
    function deleteData(dat){
        swal({
            title: '{{ __("admin.confirm")}}',
            icon: 'warning',
            buttons: {
                cancel: {
                    text: "{{ __('admin.no')}}",
                    value: null,
                    visible: true,
                    className: "btn btn-danger",
                    closeModal: true,
                },
                confirm: {
                    text: "{{ __('admin.yes')}}",
                    value: true,
                    visible: true,
                    className: "btn btn-primary",
                    closeModal: false
                }
            },
            closeOnEsc: false,
            closeOnClickOutside: false,
        }).then((value) => {
            if (value === true) {
                document.getElementById("formDelete"+dat).submit();
            }
        }).catch(err => {
            if (err) {
                swal("Oops!", err, "error");
            } else {
                swal.stopLoading();
                swal.close();
            }
        });
    }
</script>
@endsection

resources/views/admin/users/permissions.blade.php
<?php
$permissions=config('permissions');
?>
<div class="table-responsive mb-3">
    <table class="table table-bordered roles">
        <thead>
            <tr>
                <th scope="col">{{ __('admin.feature') }}</th>
                <th scope="col">{{ __('admin.access') }}</th>

            </tr>
        </thead>
        <tbody>
            @foreach ($permissions  as $feature => $permission)
            <tr data-name="{{ $feature }}">
                <th scope="row">{{ $permission['name'] }}</th>
                <td >
                    <div class="form-group m-b-0 ">
                        @foreach ($permission['access'] as $access => $name)
                        <?php
                        $checked = '';
                        $disabled = '';
                        if(( isset($user) && $user->roles()=='admin')||
                                (is_array($name) && isset($name['not_applicable']) && $name['not_applicable'])
                        ){
                        $disabled = ' disabled ';
                        }elseif (
                            (isset($user) && Helpers::user_access($access, $feature, $user->id))
                            || isset($role) && Helpers::has_role_permission($role->id, $access, $feature))
                        {
                        $checked = ' checked ';
                        }
                        ?>

                        <div class="checkbox checkbox-success">
                            <input id="{{ $feature.'_'.$access }}"
                            type="checkbox" name="permissions[{{ $feature }}][]"
                            value="{{ $access }}" {{ $checked }} {{ $disabled }}
                            {{ $access=='viewAny' ? 'data-can-view':'' }}
                            {{ $access=='view' ? 'data-can-view-own':'' }}
                            <?php if(is_array($name) && isset($name['not_applicable']) && $name['not_applicable']){ ?> data-not-applicable="true" <?php } ?>
                            >
                            <label for="{{ $feature.'_'.$access }}">{{ !is_array($name) ? $name : $name['name'] }}</label>
                        </div>
                        @endforeach
                    </div>
                </td>

            </tr>
            @endforeach
        </tbody>
    </table>
</div>