routes/admin.php
<?php

use App\Helpers\Helper;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\Dashboard;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::Group(
    [
        'prefix' => Helper::option('admin_path', 'admin'),
        'middleware' => Helper::option('verify_email') === '1' ? ['verified', 'auth'] : ['auth']
    ],
    function () {
        Route::get('/', [Dashboard::class, 'index'])->name('AppDashboard');
        Route::resource('roles', RoleController::class);
        Route::resource('users', UserController::class);
        Route::get('users/deactivate/{user}', [UserController::class, 'deactivate'])->name('users.deactivate');
        Route::get('users/activate/{user}', [UserController::class, 'activate'])->name('users.activate');
        Route::get('users/role_changed/{role}', [UserController::class, 'role_changed'])->name('users.role_changed');
        Route::get('settings', [SettingController::class, 'index'])->name('settings.index');
        Route::post('settings/general', [SettingController::class, 'general'])->name('settings.general');
        Route::get('settings/email', [SettingController::class, 'email'])->name('settings.email.get');
        Route::post('settings/email', [SettingController::class, 'email'])->name('settings.email');
        Route::get('settings/authentication', [SettingController::class, 'authentication'])->name('settings.authentication.get');
        Route::post('settings/authentication', [SettingController::class, 'authentication'])->name('settings.authentication');
        Route::get('settings/localization', [SettingController::class, 'localization'])->name('settings.localization.get');
        Route::post('settings/localization', [SettingController::class, 'localization'])->name('settings.localization');
        Route::get('settings/menage-site', [SettingController::class, 'managesite'])->name('settings.menagesite.get');
        Route::post('settings/menage-site', [SettingController::class, 'managesite'])->name('settings.managesite');
        Route::get('profile', [UserController::class, 'profile'])->name('profile');
        Route::post('profile', [UserController::class, 'update_profile'])->name('update_profile');

    }
);

routes/user.php
<?php

use App\Helpers\Helper;
use Illuminate\Support\Facades\Route;

Route::Group(
    [
        'prefix' => Helper::option('user_path', 'user'),
        'middleware' => Helper::option('verify_email') === '1' ? ['verified', 'auth'] : ['auth']
    ],
    function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('UserDashboard');
    }
);

routes/web.php
<?php

use App\Helpers\Helper;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return redirect()->route('AppDashboard');
})->name('home');


require __DIR__ . '/auth.php';
require __DIR__ . '/admin.php';
require __DIR__ . '/user.php';

resources/views/admin/layout/action.blade.php
@php
$init = '';
$act = [];
if(isset($link) and is_array($link)){
foreach ((array)$link as $actions) {
    $title = 'link';
    $class = 'text-info';
    $link = '#';
    $onclick = '';
    if (array_key_exists("title", $actions)) {
        $title = $actions['title'];
    }
    if (array_key_exists("class", $actions)) {
        $class = $actions['class'];
    }
    if (array_key_exists("link", $actions)) {
        $link = $actions['link'];
    }
    if (array_key_exists("onclick", $actions)) {
        $link = 'javascript::';
        $onclick = 'onclick="' . $actions['onclick'] . '"';
    }
    $act[] = "<a class='" . $class . "' href='" . $link . "'" . $onclick . ">" . $title . "</a>";
}
$init     = implode(" | ", $act);
}
@endphp
<div class="row-option"><?php echo $init ;?></div>

resources/views/admin/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@yield('title',Helpers::option('site_title',@env('APP_NAME')))</title>
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    @include('admin.layout.style')
    @yield('style')
</head>

<body class="adminbody">

    <div id="main">


        @include('admin.layout.header')
        @include('admin.layout.sidebar')

        <div class="content-page">
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="breadcrumb-holder">
                                <h1 class="main-title float-left">@yield('title')</h1>
                                <ol class="breadcrumb float-right">
                                    @yield('breadcrumb')
                                </ol>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                    <!-- end row -->
                    @yield('content')
                    <!-- end row -->

                </div>
                <!-- END container-fluid -->

            </div>
        </div>
        <!-- END content-page -->
        @include('admin.layout.footer')
        @include('admin.layout.script')
        @yield('script')
    </div>
    <!-- END main -->

</body>

</html>

resources/views/admin/layout/filemanager.blade.php
@section('style')
<meta name="csrf-token" content="{{ csrf_token() }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="{{ asset('vendor/file-manager/css/file-manager.css') }}">
@endsection
<div id="fm" style="height: 600px;"></div>

@section('script')
<script src="{{asset('admin/plugins/datatables/datatables.min.js')}}"></script>
<script src="{{asset('admin/plugins/sweet-alert/sweetalert.min.js')}}"></script>
<script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>

resources/views/admin/layout/footer.blade.php
<footer class="footer">
    <span class="text-right">
        Copyright <a target="_blank" href="#">Your Company</a>
    </span>
    <span class="float-right">
        Powered by <a target="_blank" href="#"><b>Your Website</b></a>
    </span>
</footer>

resources/views/admin/layout/header.blade.php
        <!-- top bar navigation -->
        <div class="headerbar">

            <!-- LOGO -->
            <div class="headerbar-left">
                <a href="{{ route('AppDashboard') }}" class="logo">
                    <img alt="Logo" src="{{ asset('admin-style/images/logo.png') }}" />
                    <span>{{__('admin.panel')}}</span>
                </a>
            </div>

            <nav class="navbar-custom">

                <ul class="list-inline float-right mb-0">
                    <li class="list-inline-item dropdown notif">
                        <a class="nav-link dropdown-toggle nav-user" data-toggle="dropdown" href="#" aria-haspopup="false" aria-expanded="false">
                            <img src="{{ asset('admin-style/images/avatars/admin.png') }}" alt="Profile image" class="avatar-rounded"> <small>{{ Auth::user()->name }}</small>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                            <!-- item-->
                            <a href="{{route('profile')}}" class="dropdown-item notify-item">
                                <i class="fas fa-user"></i>
                                <span>{{ __('admin.profile') }}</span>
                            </a>

                            <!-- item-->
                            <a href="{{ route('logout') }}" class="dropdown-item notify-item"
                                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                                <i class="fas fa-power-off"></i>
                                <span>{{ __('admin.logout') }}</span>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </a>
                        </div>
                    </li>

                </ul>

                <ul class="list-inline menu-left mb-0">
                    <li class="float-left">
                        <button class="button-menu-mobile open-left">
                            <i class="fas fa-bars"></i>
                        </button>
                    </li>

                    <li class="float-left d-none d-sm-block">
                        <a class="button-menu-mobile" target="_blank" title="Go to website" href="/">
                            <i class="fas fa-laptop"></i>
                        </a>
                    </li>
                </ul>

            </nav>

        </div>
        <!-- End Navigation -->

resources/views/admin/layout/script.blade.php
<script src="{{ asset('admin-style/js/modernizr.min.js') }}"></script>
<script src="{{ asset('admin-style/js/jquery.min.js') }}"></script>
<script src="{{ asset('admin-style/js/moment.min.js') }}"></script>

<script src="{{ asset('admin-style/js/popper.min.js') }}"></script>
<script src="{{ asset('admin-style/js/bootstrap.min.js') }}"></script>

<script src="{{ asset('admin-style/js/detect.js') }}"></script>
<script src="{{ asset('admin-style/js/fastclick.js') }}"></script>
<script src="{{ asset('admin-style/js/jquery.blockUI.js') }}"></script>
<script src="{{ asset('admin-style/js/jquery.nicescroll.js') }}"></script>

<!-- App js -->
<script src="{{ asset('admin-style/js/admin.js') }}"></script>
<script src="{{ asset('admin-style/js/main.js') }}"></script>

resources/views/admin/layout/sidebar.blade.php
<div class="left main-sidebar">

    <div class="sidebar-inner leftscroll">

        <div id="sidebar-menu">

            <ul>

                <li class="submenu">
                    <a class="{{ Route::currentRouteName()=='AppDashboard' ? 'active' :'' }} subdrop" href="{{route('AppDashboard')}}">
                        <i class="fas fa-bars"></i>
                        <span>{{__('admin.dashboard')}}</span>
                    </a>
                </li>
                @if (Gate::allows('accessView', 'roles') || Gate::allows('accessView', 'users') || Gate::allows('accessView', 'settings'))
                <div class="h6 mt-4 p-3 text-white bg-dark"><span>{{ trans('admin.setup') }}</span></div>
                @endif
                @can('accessView', 'users')
                @php
                    $currentFolder = "users"; // Put folder name here
                    $PathCurrentFolder = substr($urlPath, 0, strlen($currentFolder));

                @endphp
                <li class="submenu">
                    <a class="{{ $PathCurrentFolder==$currentFolder ? 'active' : '' }}" href="{{route('users.index')}}">
                        <i class="fas fa-users"></i>
                        <span>{{ trans('admin.users') }}</span>
                    </a>
                </li>
                @endcan
                @can('accessView', 'roles')
                @php
                    $currentFolder = "roles"; // Put folder name here
                    $PathCurrentFolder = substr($urlPath, 0, strlen($currentFolder));
                @endphp
                <li class="submenu">
                    <a class="{{ $PathCurrentFolder==$currentFolder ? 'active' : '' }}" href="{{route('roles.index')}}">
                        <i class="fas fa-user-check"></i>
                        <span>{{ trans('admin.roles') }}</span>
                    </a>
                </li>
                @endcan
                 @can('accessView', 'settings')
                <?php
                $currentFolder = "settings"; // Put folder name here
                $PathCurrentFolder = substr($urlPath, 0, strlen($currentFolder));
                ?>
                <li class="submenu">
                    <a class="{{ $PathCurrentFolder==$currentFolder ? 'active' : '' }}" href="{{route('settings.index')}}">
                        <i class="fas fa-cogs"></i>
                        <span>{{ trans('admin.settings') }}</span>
                    </a>
                </li>
                @endcan
            </ul>

            <div class="clearfix"></div>

        </div>

        <div class="clearfix"></div>

    </div>

</div>
<!-- End Sidebar -->

resources/views/admin/layout/style.blade.php
 <link rel="shortcut icon" href="{{ asset('admin-style/images/favicon.ico') }}">
<!-- Bootstrap CSS -->
<link href="{{ asset('admin-style/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />

<!-- Font Awesome CSS -->
<link href="{{ asset('admin-style/font-awesome/css/all.css') }}" rel="stylesheet" type="text/css" />

<!-- Custom CSS -->
<link href="{{ asset('admin-style/css/style.css') }}" rel="stylesheet" type="text/css" />